### ISSUE TITLE
Emojis in '/t2s' cause issues

### ISSUE THREAD

**Issue by robcalcroft** [zaccolley/roborob#4]

**Comment by robcalcroft** [comment]
@zaccolley how do we wanna tackle this? Emoji interpretation?? or just respond with not allowed

**Comment by robcalcroft** [comment]
https://github.com/iamcal/emoji-data/blob/master/emoji.json

**Comment by zoetrope69** [comment]
get the safe names of the emoji and use them as keywords

**Comment by robcalcroft** [comment]
for the gif? or t2s? or both

**Comment by robcalcroft** [comment]
ref e2cb00f6f84b353c9bf898ac1c8f56042ddc4f66

**Comment by robcalcroft** [comment]
See https://github.com/zaccolley/roborob/pull/5

**Comment by zoetrope69** [comment]
fixed with #5
